# Generated by Django 2.1.7 on 2019-05-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_auto_20190526_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='models/images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.Brand')),
            ],
        ),
    ]
